import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Bussiness Card App | Flora Li</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-[calc(100vh-4rem)] flex-col justify-center bg-gradient-to-br from-[#d299c2] to-[#fef9d7]">
        {!sessionData && (
          <button className="flex justify-center items-center gap-4 rounded-full bg-black/10 px-10 py-3 no-underline font-semibold text-black transition hover:bg-black/20">
            <img
              width={30}
              height={30}
              src="https://img.icons8.com/stickers/100/google-logo.png"
              alt="google-logo"
            />
            Sign in with Google
          </button>
        )}
      </main>
    </>
  );
}
